### ISSUE TITLE
Refactoring Motor/Dispenser Library

### ISSUE THREAD

**Issue by DavidFederl** [ES-EDU-SIEGMA/Embedded-Controller#49]

**Comment by YULEMING** [comment]
```c
void dispenserChangeStates(dispenser_t *dispenser) {
    if (!motorIsCommunicating(dispenser->address)) {
        dispenser->state = errorState_t;
    }
    dispenser->state = dispenser->state.function(dispenser);
}
```
Can we move:
```c
if (!motorIsCommunicating(&(dispenser->motor))) {
        dispenser->state = errorState_t;
    }
```
before `do while`:
```c
void processMessage(char *message, size_t messageLength) {
    uint8_t dispensersTrigger = 0;
    bool triggeredDispensers[NUMBER_OF_DISPENSERS]={false};

    PRINT_DEBUG("Process message len: %u", messageLength)
    PRINT_DEBUG("Message: %s", message)
    for (uint8_t i = 0; i < 4; ++i) {
        uint32_t dispenserHaltTimes = parseInputString(&message);
        if (dispenserHaltTimes > 0) {
            dispensersTrigger++;
            triggeredDispensers[i] = true;
        }
        dispenserSetHaltTime(&dispenser[i], dispenserHaltTimes);
    }

    do {
        resetWatchdogTimer();
        for (uint8_t i = 0; i < NUMBER_OF_DISPENSERS; ++i) {
            if (triggeredDispensers[i] == true) {
                dispenserChangeStates(&dispenser[i]);
                if (getDispenserState(&dispenser[i]) == DISPENSER_STATE_SLEEP) {
                    triggeredDispensers[i] = false;
                }
            }
        }
        // When all dispensers are finished, they are in the state sleep
    } while (!dispenserAllInSleepState(dispenser, NUMBER_OF_DISPENSERS));
}
```
Check 4 motors before starting to work? In order to reduce one more sleep in the end of `TMC2209_read`.

**Comment by HuangQing23** [comment]
> ### develop - [dispenser.c](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/blob/develop/src/dispenser/dispenser.c#L59)
> ```c
> void dispenserChangeStates(dispenser_t *dispenser) {
>     if (!motorIsCommunicating(dispenser->address)) {
>         dispenser->state = errorState_t;
>     }
>     dispenser->state = dispenser->state.function(dispenser);
> }
> ```
> 
> Can we move:
> 
> ```c
> if (!motorIsCommunicating(&(dispenser->motor))) {
>         dispenser->state = errorState_t;
>     }
> ```
> 
> before `do while`:
> 
> ```c
> void processMessage(char *message, size_t messageLength) {
>     uint8_t dispensersTrigger = 0;
>     bool triggeredDispensers[NUMBER_OF_DISPENSERS]={false};
> 
>     PRINT_DEBUG("Process message len: %u", messageLength)
>     PRINT_DEBUG("Message: %s", message)
>     for (uint8_t i = 0; i < 4; ++i) {
>         uint32_t dispenserHaltTimes = parseInputString(&message);
>         if (dispenserHaltTimes > 0) {
>             dispensersTrigger++;
>             triggeredDispensers[i] = true;
>         }
>         dispenserSetHaltTime(&dispenser[i], dispenserHaltTimes);
>     }
>     // move it to here
>     do {
>         resetWatchdogTimer();
>         for (uint8_t i = 0; i < NUMBER_OF_DISPENSERS; ++i) {
>             if (triggeredDispensers[i] == true) {
>                 dispenserChangeStates(&dispenser[i]);
>                 if (getDispenserState(&dispenser[i]) == DISPENSER_STATE_SLEEP) {
>                     triggeredDispensers[i] = false;
>                 }
>             }
>         }
>         // When all dispensers are finished, they are in the state sleep
>     } while (!dispenserAllInSleepState(dispenser, NUMBER_OF_DISPENSERS));
> }
> ```
> 
> Check 4 motors before starting to work? In order to reduce one more sleep in the end of `TMC2209_read`.

Yeah it seems like we can do it. And there is sth about calling the static parameter errorstate_t. If it does work, then we may reduce the sleep_us(20) in the end of  TMC2209_read. I will test it.

**Comment by HuangQing23** [comment]
Tested the code and it works properly by move this part:

if (!motorIsCommunicating(&(dispenser->motor))) {
        dispenser->state = errorState_t;
    }

from function 'dispenserChangeStates(dispenser_t *dispenser)' and add it to a new function:
dispenserErrorStateCheck(dispenser_t *dispenser) with a for loop before do while
