### ISSUE TITLE
Prepare a draft for interfaces for dispenser/motor libs

### ISSUE THREAD

**Issue by glencoe** [ES-EDU-SIEGMA/Embedded-Controller#50]
What are the problems with these libs at the moment?
How should the new interfaces look like to fix these issues?
What are functions and function signatures for each of these libs?
What is the expected behaviour for these functions?

Finally discuss the draft in the group and finalize the interfaces.

**Comment by HuangQing23** [comment]
Some questions from last week
1.Why we use dispenser Emergency stop?
We just use it for testing. It should not be in the public version.

2.Should motor get the time we calculate or just execute the command we preseted in the code?

3.In motor lib, function setUpEnablePin, 
MOTOR_ENABLE_PINT_0-->2
MOTOR_ENABLE_PINT_1-->3
MOTOR_ENABLE_PINT_2-->6
MOTOR_ENABLE_PINT_3-->7
In the datasheet and pcb design we can see that, 2-->6 and 3-->7 is correct, but why the function still work when
MOTOR_ENABLE_PINT_0-->2
MOTOR_ENABLE_PINT_1-->3
when it should be MOTOR_ENABLE_PINT_0-->4 and MOTOR_ENABLE_PINT_1-->5?

**Comment by HuangQing23** [comment]
In motor :
1.We can change motor_t --> Motor_Entity or ?
2.For these two functions 'enableMotorByPin' and 'disableMotorByPin',we can wrap these two functions into one
3.Shall we delete function'motorIsCommunicating' cause we can just use TMC2209_isSetupAndCommunicating(&motor->tmc2209) instead or we can use an explanatory variable like 'communicationState'
4.We should delete the repetitive parts of  'moveMotorUp', 'moveMotorDown', 'stopMotor'
5.Maybe we should change the names of TMC2209_moveAtVelocity, cause it's used for 'stopMotor'

In dispenser :
for 'dispenserStateCode_t dispenserGetStateCode':
1.shall we change dispenserGetStateCode-->getDispenserState
2.delete the 'else', keep the 'if' to reduce nesting

for 'dispenserEmergencyStop':
1.We should delete it in the public version

for 'resetDispenserPosition':
1.I think we should do something in the while loop to make sure if limitswitch broken then we can stop or avoid a crisis 
(when we can use torque or something to get a exact position for reset,we shall delete this function or change it )

for 'dispenserSetAllToSleepState':
we better change it to 'dispenserAllInSleepState' 

also for 'dispenserState_t upState(dispenser_t *dispenser)': 
we should pay attention to this code segment----
if (!limitSwitchIsClosed(dispenser->limitSwitch)) {
        dispenser->stepsDone++;
    }

In rondell :
1. We can change createRondell -->setUpRondell, in view of the code in motor. And change setUpRondell -->createRondell 

In left_controller library and rondell controller :
1. We should put both 'initHardware(false)' and 'establishConnectionWithController("LEFT")' out of the main function. 
So we can write a function in helper that conclude both these two funtions.
(Shall we also put in the watchdog?)
2. There are different 'initDispenser' in left_controller and rondell controller , we should separate them

**Comment by HuangQing23** [comment]
We should change the code in 'handleMessage' or 'if (isLineEnd(input))' to solve the situation when we want to swtich to another controller

**Comment by HuangQing23** [comment]
1.Did some renaming to make the function more readable.
2.Moved the states and motorDoStep(used to be dispenserDoStep) and dispenserAllInSleepState from dispenser library to motor library and fix the headers.
3.Write a function for 'calibrated' to make sure 'initDispenser()' and 'initRondellDispenser()' is successful. But it seems better to move it to dispenser later.
4.Add a function 'isIdentifier' in helper(handleMessage) for switch to another controller, but based on some size problem it need some more changes, but it's ok if we don't enter words except 'i'.
5.Tried to change the function 'motorIsCommunicating(Motor_t *motor)' but it seems some problems happened. We can discuss it later.

**Comment by HuangQing23** [comment]
Should do cleaner separations for the structure of dispenser and motor.

**Comment by HuangQing23** [comment]
Due to some medical condition I delayed this commit then I clicked the wrong button which made task 49 create its own branch so I had to link the branch to this task first but it seems like my account can't solve this problem.

**Comment by YULEMING** [comment]
Have you built the `left` successfully, I tried but failed on branch [refactoring the code](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/tree/refactoring-the-code).

**Comment by HuangQing23** [comment]
> Have you built the `left` successfully, I tried but failed on branch [refactoring the code](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/tree/refactoring-the-code).

Yeah I built it without reporting an error. But I will check again.
