### ISSUE TITLE
Improve Unit Test Coverage

### ISSUE THREAD

**Issue by YULEMING** [ES-EDU-SIEGMA/Embedded-Controller#58]
* [x] Repair Unit Test. Fix bugs and build it successfully.
* [x] Figure out the current coverage of Unit Test.
* [ ] Extent the coverage of Unit Test.

**Comment by YULEMING** [comment]
#### Repair Unit Test. Fix bugs and build it successfully.
* After fixing some naming and declaration errors, the unit-test can be built successfully now.
#### Figure out the current coverage of Unit Test.
It tests:
* dispenser
  * the structure of the dispenser (working)
  * the cycle of the dispenser (not working)

**Comment by YULEMING** [comment]
### Extent the coverage of Unit Test.
Tasks list, from bottom to top, easy to hard:
* [ ] Limit switch
* [ ] Hardware helper
* [ ] serial UART
* [ ] tmc2209
* [ ] motor
* [ ] dispenser
* [ ] Rondell
* [ ] controller
* [ ] rondell controller

**Comment by YULEMING** [comment]
Yes, just pushed [here](https://github.com/ES-EDU-SIEGMA/Embedded-Controller/tree/%2358-fix-improve-unit-test). But it's not finished yet. The CMakeLists.txt will keep changing and may not be able to be built directly.

**Comment by DavidFederl** [comment]
Please see #81
