### ISSUE TITLE
Pass velocity for motor to setUp function

### ISSUE THREAD

**Issue by kamilloo1** [ES-EDU-SIEGMA/Embedded-Controller#88]
Because the rotation of the rondell requires a slower speed then the moving up of the lever of the dispenser, we need the motors to operate at two different speeds. The Dispenser requires a higher speed to make the torque detection work.
**Right now the velocity to the motor is passed via `#define` which affects the motor speed for all use cases.** To solve the problem, the velocity for the motor should be set via variables during setUp and stored inside the struct that holds the motor configuration!

**Comment by DavidFederl** [comment]
See #102
